### ISSUE TITLE
Remove invalid files

### ISSUE THREAD

**Issue by jcfr** [lancelevine/SlicerDRRGenerator#1]
These files should be removed

```
CMakeLists1.txt
CMakeLists - Copy (2).txt
DDRGenerator2.png
```

Also, if this widget is not implemented it should probably be removed: `qSlicerDRRGeneratorModuleFooBarWidget.h`

**Comment by lancelevine** [comment]
I removed the requested files.

I would like to keep the widget for future expansion if possible.
